# railway.toml

[build]
builder = "NIXPACKS"
buildCommand = "pip install -r requirements.txt"

[build.nixpacks]
packages = ["libgl1", "libglib2.0-0", "ffmpeg", "libsm6", "libxext6"]


[deploy]
start = "gunicorn -w 4 -b 0.0.0.0:5000 app:app"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[service]
internalPort = 5000
healthcheckPath = "/api/model/health"
healthcheckTimeout = 300