# railway.toml

[build]
builder = "NIXPACKS"
buildCommand = "pip install -r requirements.txt"

[build.nixpacks]
packages = ["libgl1", "libglib2.0-0", "ffmpeg", "libsm6", "libxext6"]


[deploy]
startCommand = "gunicorn app:app --bind 0.0.0.0:$PORT --workers 4"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[service]
internalPort = 5000
healthcheckPath = "/api/model/health"
healthcheckTimeout = 300